---
name: "notify_user"
pack: "chatops"
enabled: true
description: "Notification rule to send results of action executions to stream for chatops"
trigger:
  type: "core.st2.generic.notifytrigger"
criteria:
  trigger.route:
    pattern: "hubot"
    type: "equals"
action:
  ref: chatops.notify_user
  parameters:
    user: "{{trigger.data.user}}"
    execution_id: "{{trigger.execution_id}}"
